### ISSUE TITLE
[plan] 2주차 개발 일정 논의

### ISSUE THREAD

**Issue by hyeonjoo** [ReactMasters/todolist#44]
## Feature description

2주차 개발 일정을 논의합니다.

## Todos
- [x] 회원가입
  - [x] #62
  - [x] #61
    - [x] email, password validation
    - [x] create union return type
    - [x] return initial jwt
  - [x] #75
  - [x] #71
- [x] 로그인
  - [x] #52
  - [x] #53
  - [x] #51
    - [x] validate email & password
    - [x] return jwt token and user
  - [x] #54
  - [x] #64
  - [x] #65
    - [x] get token from header(cookie) -
    - [x] validator jwt 
    - [x] return user
  - [x] [web] me 쿼리에서 받은 유저정보를 화면에 나타낸다.
- [x] 로그아웃
  - [x] [web] 로그아웃 버튼을 누른다.
- [x] 투두아이템 만들기 / 보여주기
  - [x] #56
  - [x] #89

**Comment by JeGwan** [comment]
#96 에서 남은 작업들은 정의되는 것 같아요. 이 이슈는 클로즈할게요.
