### ISSUE TITLE
[api] user login mutation / return jwt token

### ISSUE THREAD

**Issue by JeGwan** [ReactMasters/todolist#51]
## tasks

- [x] `createUser` resolver
  - [x] email, password validation
  - [x] create union return type
  - [x] return initial jwt
- [ ] `me` resolver
  - [ ] get token from header(cookie) -
  - [ ] validator jwt 
  - [ ] return user
- [x] `login` resolver
  - [x] validate email & password
  - [x] return jwt token and user
